// Source of the service worker, generated at build time (see vite.config.ts)
// with the exact list of files of that build, so the app (bot included) works
// offline after the first visit. Kept as a pure function for testing.

/**
 * The service worker script.
 * - install: caches every file of the build under a versioned cache name;
 * - activate: deletes caches of older versions;
 * - fetch: same-origin GET requests come from the cache first (navigations get
 *   the cached app page; Vary headers are ignored so crossorigin requests match),
 *   anything else goes to the network;
 * - a new version waits until the page asks it to take over ("skip-waiting"),
 *   so the user decides when to reload.
 */
export function serviceWorkerSource(files: readonly string[], version: string): string {
  return `// Generated by the dorkchess build. Do not edit.
const CACHE = ${JSON.stringify(`dorkchess-${version}`)};
const FILES = ${JSON.stringify(files)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('dorkchess-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(caches.match('./', { ignoreVary: true }).then((page) => page || fetch(request)));
    return;
  }
  // ignoreVary: crossorigin requests (module script, stylesheet) carry an Origin header
  // that the cached copies were fetched without; a "Vary: Origin" response would not match.
  event.respondWith(caches.match(request, { ignoreVary: true }).then((hit) => hit || fetch(request)));
});
`;
}

/** Short stable hash of the file list (cache version): changes whenever a hashed file name changes. */
export function versionOf(files: readonly string[]): string {
  let h = 2166136261;
  for (const ch of files.join('|')) h = Math.imul(h ^ ch.charCodeAt(0), 16777619);
  return (h >>> 0).toString(36);
}
